/data/callbackext/ Directory Reference.TH "/data/callbackext/ Directory Reference" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/ Directory Reference \- 
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBContainer\fP"
.br
.ti -1c
.RI "directory \fBDelegateN\fP"
.br
.ti -1c
.RI "directory \fBFunctorN\fP"
.br
.ti -1c
.RI "directory \fBTests\fP"
.br
.in -1c
