/data/callbackext/Container/AlgorithmExt.hpp File Reference.TH "/data/callbackext/Container/AlgorithmExt.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
NAME
/data/callbackext/Container/AlgorithmExt.hpp -
SYNOPSIS
#include <algorithm>
Namespaces
namespace stdext
Defines
#define GUARD_ALGORITHM_EXT_HPP_INCLUDED 1
Functions
template<typename ContainerType, typename Functor> void foreach (ContainerType &cont, Functor func)
template<typename ContainerType, typename Functor> void foreach_reverse (ContainerType &cont, Functor func)
Define Documentation
#define GUARD_ALGORITHM_EXT_HPP_INCLUDED 1
Definition at line 19 of file AlgorithmExt.hpp.
Function Documentation
template<typename ContainerType, typename Functor> void foreach (ContainerType & cont, Functor func)
Definition at line 27 of file AlgorithmExt.hpp.
Referenced by DL::DelegateList::call(), DL::DelegateList::operator()(), DL::Associative< KeyType, Compare >::~Associative(), and DL::DelegateList::~DelegateList().
template<typename ContainerType, typename Functor> void foreach_reverse (ContainerType & cont, Functor func)
Definition at line 33 of file AlgorithmExt.hpp.
Referenced by DL::DelegateList::reverse_call().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.