/data/callbackext/Container/AlgorithmExt.hpp File Reference.TH "/data/callbackext/Container/AlgorithmExt.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/Container/AlgorithmExt.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstdext\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_ALGORITHM_EXT_HPP_INCLUDED\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename ContainerType, typename Functor> void \fBforeach\fP (ContainerType &cont, Functor func)"
.br
.ti -1c
.RI "template<typename ContainerType, typename Functor> void \fBforeach_reverse\fP (ContainerType &cont, Functor func)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_ALGORITHM_EXT_HPP_INCLUDED   1"
.PP
Definition at line 19 of file AlgorithmExt.hpp.
.SH "Function Documentation"
.PP 
.SS "template<typename ContainerType, typename Functor> void foreach (ContainerType & cont, Functor func)"
.PP
Definition at line 27 of file AlgorithmExt.hpp.
.PP
Referenced by DL::DelegateList::call(), DL::DelegateList::operator()(), DL::Associative< KeyType, Compare >::~Associative(), and DL::DelegateList::~DelegateList().
.SS "template<typename ContainerType, typename Functor> void foreach_reverse (ContainerType & cont, Functor func)"
.PP
Definition at line 33 of file AlgorithmExt.hpp.
.PP
Referenced by DL::DelegateList::reverse_call().
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
