
.PP
.TH "Blah" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blah \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBTestAFunc\fP (int value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int Blah::TestAFunc (int value)\fC [inline]\fP"
.PP
Definition at line 33 of file DelegateTest1.cc.

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
