/data/callbackext/DelegateN/DelegateN.hpp File Reference.TH "/data/callbackext/DelegateN/DelegateN.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/DelegateN/DelegateN.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Delegate0.hpp'\fP
.br
\fC#include 'Delegate1.hpp'\fP
.br
\fC#include 'Delegate2.hpp'\fP
.br
\fC#include 'Delegate3.hpp'\fP
.br
\fC#include 'Delegate4.hpp'\fP
.br
\fC#include 'Delegate5.hpp'\fP
.br
\fC#include 'Delegate6.hpp'\fP
.br
\fC#include 'Delegate7.hpp'\fP
.br
\fC#include 'Delegate8.hpp'\fP
.br
\fC#include 'Delegate9.hpp'\fP
.br
\fC#include 'Delegate10.hpp'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_DELEGATES_DELEGATEN_HPP\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_DELEGATES_DELEGATEN_HPP   1"
.PP
Definition at line 19 of file DelegateN.hpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
