/data/callbackext/Tests/DelegateTest3.cc File Reference.TH "/data/callbackext/Tests/DelegateTest3.cc" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/Tests/DelegateTest3.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '../DelegateN/DelegateN.hpp'\fP
.br
\fC#include '../Container/Associative.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFoobar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
.PP
Definition at line 49 of file DelegateTest3.cc.
.PP
References DL::create_delegate(), DL::Associative< KeyType, Compare >::emit(), and DL::Associative< KeyType, Compare >::insert().
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
