/data/callbackext/Tests/DelegateTest3.cc File Reference.TH "/data/callbackext/Tests/DelegateTest3.cc" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
NAME
/data/callbackext/Tests/DelegateTest3.cc -
SYNOPSIS
#include <iostream>
#include '../DelegateN/DelegateN.hpp'
#include '../Container/Associative.hpp'
Classes
struct Foobar
Functions
int main ()
Function Documentation
int main ()
Definition at line 49 of file DelegateTest3.cc.
References DL::create_delegate(), DL::Associative< KeyType, Compare >::emit(), and DL::Associative< KeyType, Compare >::insert().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.