/data/callbackext/DelegateN/Delegate1.hpp File Reference.TH "/data/callbackext/DelegateN/Delegate1.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/DelegateN/Delegate1.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'DelegateBase.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDL\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_DELGATES_DELEGATE1_HPP_INCLUDED\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class ReturnType, class ClassType, class Param1> \fBDelegateObj\fP \fBcreate_delegate\fP (ClassType &obj, ReturnType(ClassType::*Meth)(Param1), Param1 &param1)"
.br
.ti -1c
.RI "template<class ReturnType, class ClassType, class Param1> \fBDelegateObj\fP \fBcreate_delegate\fP (ClassType *obj, ReturnType(ClassType::*Meth)(Param1), Param1 &param1)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_DELGATES_DELEGATE1_HPP_INCLUDED   1"
.PP
Definition at line 19 of file Delegate1.hpp.
.SH "Function Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1> \fBDelegateObj\fP create_delegate (ClassType * obj, ReturnType(ClassType::*)(Param1) Meth, Param1 & param1)"
.PP
Definition at line 63 of file Delegate1.hpp.
.SS "template<class ReturnType, class ClassType, class Param1> \fBDelegateObj\fP create_delegate (ClassType & obj, ReturnType(ClassType::*)(Param1) Meth, Param1 & param1)"
.PP
Definition at line 57 of file Delegate1.hpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
