/data/callbackext/Tests/DelegateTest1.cc File Reference.TH "/data/callbackext/Tests/DelegateTest1.cc" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
NAME
/data/callbackext/Tests/DelegateTest1.cc -
SYNOPSIS
#include <string>
#include <iostream>
#include '../DelegateN/Delegate1.hpp'
#include '../Container/DelegateList.hpp'
Functions
int main ()
Function Documentation
int main ()
Definition at line 37 of file DelegateTest1.cc.
References DL::DelegateList::add(), DL::DelegateList::call(), and DL::create_delegate().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.