/data/callbackext/DelegateN/DelegateBase.hpp File Reference.TH "/data/callbackext/DelegateN/DelegateBase.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/DelegateN/DelegateBase.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDL\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_DELGATES_DELEGATE_BASE_HPP_INCLUDED\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::auto_ptr< DelegateBase > \fBDelegateObj\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_DELGATES_DELEGATE_BASE_HPP_INCLUDED   1"
.PP
Definition at line 19 of file DelegateBase.hpp.
.SH "Typedef Documentation"
.PP 
.SS "typedef std::auto_ptr<DelegateBase> \fBDL::DelegateObj\fP"
.PP
Definition at line 33 of file DelegateBase.hpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
