/data/callbackext/Tests/DelegateTest2.cc File Reference.TH "/data/callbackext/Tests/DelegateTest2.cc" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
NAME
/data/callbackext/Tests/DelegateTest2.cc -
SYNOPSIS
#include <iostream>
#include '../Container/DelegateList.hpp'
#include '../DelegateN/DelegateN.hpp'
#include '../FunctorN/FunctorN.hpp'
Functions
void test0 ()
void test1 (int i1)
void test2 (int i1, int i2)
void test3 (int i1, int i2, int i3)
void test4 (int i1, int i2, int i3, int i4)
void test5 (int i1, int i2, int i3, int i4, int i5)
void test6 (int i1, int i2, int i3, int i4, int i5, int i6)
void test7 (int i1, int i2, int i3, int i4, int i5, int i6, int i7)
void test8 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)
void test9 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)
void test10 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)
int main ()
Function Documentation
int main ()
Definition at line 77 of file DelegateTest2.cc.
References DL::DelegateList::add(), DL::create_delegate(), test0(), test1(), test10(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
void test0 ()
Definition at line 27 of file DelegateTest2.cc.
Referenced by main().
void test1 (int i1)
Definition at line 29 of file DelegateTest2.cc.
Referenced by main().
void test10 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)
Definition at line 47 of file DelegateTest2.cc.
Referenced by main().
void test2 (int i1, int i2)
Definition at line 31 of file DelegateTest2.cc.
Referenced by main().
void test3 (int i1, int i2, int i3)
Definition at line 33 of file DelegateTest2.cc.
Referenced by main().
void test4 (int i1, int i2, int i3, int i4)
Definition at line 35 of file DelegateTest2.cc.
Referenced by main().
void test5 (int i1, int i2, int i3, int i4, int i5)
Definition at line 37 of file DelegateTest2.cc.
Referenced by main().
void test6 (int i1, int i2, int i3, int i4, int i5, int i6)
Definition at line 39 of file DelegateTest2.cc.
Referenced by main().
void test7 (int i1, int i2, int i3, int i4, int i5, int i6, int i7)
Definition at line 41 of file DelegateTest2.cc.
Referenced by main().
void test8 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)
Definition at line 43 of file DelegateTest2.cc.
Referenced by main().
void test9 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)
Definition at line 45 of file DelegateTest2.cc.
Referenced by main().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.