DL::Associative
NAME
DL::Associative -
SYNOPSIS
#include <Associative.hpp>
Public Types
typedef Compare compare_type
typedef KeyType key_type
typedef std::map< key_type, DelegateBase *, compare_type > map_type
Public Member Functions
Associative ()
virtual ~Associative ()
void insert (key_type key, DelegateObj Callback)
void emit (key_type key)
Private Attributes
std::map< key_type, DelegateBase *, compare_type > m_data
template<class KeyType, class Compare = std::less<KeyType>> class DL::Associative< KeyType, Compare >
Member Typedef Documentation
template<class KeyType, class Compare = std::less<KeyType>> typedef Compare DL::Associative< KeyType, Compare >::compare_type
Definition at line 40 of file Associative.hpp.
template<class KeyType, class Compare = std::less<KeyType>> typedef KeyType DL::Associative< KeyType, Compare >::key_type
Definition at line 41 of file Associative.hpp.
template<class KeyType, class Compare = std::less<KeyType>> typedef std::map< key_type, DelegateBase* , compare_type > DL::Associative< KeyType, Compare >::map_type
Definition at line 42 of file Associative.hpp.
Constructor & Destructor Documentation
template<class KeyType, class Compare = std::less<KeyType>> DL::Associative< KeyType, Compare >::Associative () [inline]
Definition at line 44 of file Associative.hpp.
template<class KeyType, class Compare = std::less<KeyType>> virtual DL::Associative< KeyType, Compare >::~Associative () [inline, virtual]
Definition at line 45 of file Associative.hpp.
References stdext::foreach(), and DL::Associative< KeyType, Compare >::m_data.
Member Function Documentation
template<class KeyType, class Compare = std::less<KeyType>> void DL::Associative< KeyType, Compare >::emit (key_type key) [inline]
Definition at line 53 of file Associative.hpp.
References DL::Associative< KeyType, Compare >::m_data.
Referenced by main().
template<class KeyType, class Compare = std::less<KeyType>> void DL::Associative< KeyType, Compare >::insert (key_type key, DelegateObj Callback) [inline]
Definition at line 49 of file Associative.hpp.
References DL::Associative< KeyType, Compare >::m_data.
Referenced by main().
Member Data Documentation
template<class KeyType, class Compare = std::less<KeyType>> std::map< key_type , DelegateBase* , compare_type > DL::Associative< KeyType, Compare >::m_data [private]
Definition at line 60 of file Associative.hpp.
Referenced by DL::Associative< KeyType, Compare >::emit(), DL::Associative< KeyType, Compare >::insert(), and DL::Associative< KeyType, Compare >::~Associative().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.