.TH "DL::Deleter" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Deleter \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Associative.hpp>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (typename MapType::value_type iter)"
.br
.in -1c

.SS "template<class MapType> struct DL::Deleter< MapType >"

.SH "Member Function Documentation"
.PP 
.SS "template<class MapType> void \fBDL::Deleter\fP< MapType >::operator() (typename MapType::value_type iter)\fC [inline]\fP"
.PP
Definition at line 31 of file Associative.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
