.TH "DL::Delegate3" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Delegate3 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Delegate3.hpp>\fP
.PP
Inherits \fBDL::DelegateBase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegate3\fP (ClassType *class_obj, ReturnType(ClassType::*method)(Param1, Param2, Param3), Param1 val1=Param1(), Param2 val2=Param2(), Param3 val3=Param3())"
.br
.ti -1c
.RI "virtual \fB~Delegate3\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP (Param1 val1, Param2 val2, Param3 val3)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegate3\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ClassType * \fBm_class_obj\fP"
.br
.ti -1c
.RI "ReturnType(ClassType::* \fBm_method\fP )(Param1, Param2, Param3)"
.br
.ti -1c
.RI "Param1 \fBm_val1\fP"
.br
.ti -1c
.RI "Param2 \fBm_val2\fP"
.br
.ti -1c
.RI "Param3 \fBm_val3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> class DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >"
Delegate for 3 Param
.PP
Definition at line 36 of file Delegate3.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBDelegate3\fP ()\fC [inline, private]\fP"
.PP
Definition at line 43 of file Delegate3.hpp.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBDelegate3\fP (ClassType * class_obj, ReturnType(ClassType::*)(Param1, Param2, Param3) method, Param1 val1 = \fCParam1()\fP, Param2 val2 = \fCParam2()\fP, Param3 val3 = \fCParam3()\fP)\fC [inline]\fP"
.PP
Definition at line 45 of file Delegate3.hpp.
.PP
References DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_class_obj, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_method, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val1, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val2, and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val3.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> virtual \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::~\fBDelegate3\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 53 of file Delegate3.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> void \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke (Param1 val1, Param2 val2, Param3 val3)\fC [inline]\fP"
.PP
Definition at line 58 of file Delegate3.hpp.
.PP
References DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_class_obj, and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_method.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> void \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke ()\fC [inline, virtual]\fP"
.PP
Implements \fBDL::DelegateBase\fP.
.PP
Definition at line 54 of file Delegate3.hpp.
.PP
References DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_class_obj, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_method, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val1, DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val2, and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::m_val3.
.SH "Member Data Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> ClassType* \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBm_class_obj\fP\fC [private]\fP"
.PP
Definition at line 38 of file Delegate3.hpp.
.PP
Referenced by DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Delegate3(), and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> ReturnType(ClassType::* \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBm_method\fP)(Param1, Param2, Param3)\fC [private]\fP"
.PP
Referenced by DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Delegate3(), and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> Param1 \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBm_val1\fP\fC [private]\fP"
.PP
Definition at line 40 of file Delegate3.hpp.
.PP
Referenced by DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Delegate3(), and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> Param2 \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBm_val2\fP\fC [private]\fP"
.PP
Definition at line 41 of file Delegate3.hpp.
.PP
Referenced by DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Delegate3(), and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3> Param3 \fBDL::Delegate3\fP< ReturnType, ClassType, Param1, Param2, Param3 >::\fBm_val3\fP\fC [private]\fP"
.PP
Definition at line 42 of file Delegate3.hpp.
.PP
Referenced by DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Delegate3(), and DL::Delegate3< ReturnType, ClassType, Param1, Param2, Param3 >::Invoke().

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
