.TH "DL::Delegate5" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Delegate5 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Delegate5.hpp>\fP
.PP
Inherits \fBDL::DelegateBase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegate5\fP (ClassType *class_obj, ReturnType(ClassType::*method)(Param1, Param2, Param3, Param4, Param5), Param1 val1=Param1(), Param2 val2=Param2(), Param3 val3=Param3(), Param4 val4=Param4(), Param5 val5=Param5())"
.br
.ti -1c
.RI "virtual \fB~Delegate5\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP (Param1 val1, Param2 val2, Param3 val3, Param4 val4, Param5 val5)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDelegate5\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ClassType * \fBm_class_obj\fP"
.br
.ti -1c
.RI "ReturnType(ClassType::* \fBm_method\fP )(Param1, Param2, Param3, Param4, Param5)"
.br
.ti -1c
.RI "Param1 \fBm_val1\fP"
.br
.ti -1c
.RI "Param2 \fBm_val2\fP"
.br
.ti -1c
.RI "Param3 \fBm_val3\fP"
.br
.ti -1c
.RI "Param4 \fBm_val4\fP"
.br
.ti -1c
.RI "Param5 \fBm_val5\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> class DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >"
Delegate for 5 Param
.PP
Definition at line 36 of file Delegate5.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBDelegate5\fP ()\fC [inline, private]\fP"
.PP
Definition at line 45 of file Delegate5.hpp.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBDelegate5\fP (ClassType * class_obj, ReturnType(ClassType::*)(Param1, Param2, Param3, Param4, Param5) method, Param1 val1 = \fCParam1()\fP, Param2 val2 = \fCParam2()\fP, Param3 val3 = \fCParam3()\fP, Param4 val4 = \fCParam4()\fP, Param5 val5 = \fCParam5()\fP)\fC [inline]\fP"
.PP
Definition at line 47 of file Delegate5.hpp.
.PP
References DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_class_obj, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_method, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val1, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val2, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val3, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val4, and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val5.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> virtual \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::~\fBDelegate5\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 58 of file Delegate5.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> void \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke (Param1 val1, Param2 val2, Param3 val3, Param4 val4, Param5 val5)\fC [inline]\fP"
.PP
Definition at line 63 of file Delegate5.hpp.
.PP
References DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_class_obj, and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_method.
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> void \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke ()\fC [inline, virtual]\fP"
.PP
Implements \fBDL::DelegateBase\fP.
.PP
Definition at line 59 of file Delegate5.hpp.
.PP
References DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_class_obj, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_method, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val1, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val2, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val3, DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val4, and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::m_val5.
.SH "Member Data Documentation"
.PP 
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> ClassType* \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_class_obj\fP\fC [private]\fP"
.PP
Definition at line 38 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> ReturnType(ClassType::* \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_method\fP)(Param1, Param2, Param3, Param4, Param5)\fC [private]\fP"
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> Param1 \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_val1\fP\fC [private]\fP"
.PP
Definition at line 40 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> Param2 \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_val2\fP\fC [private]\fP"
.PP
Definition at line 41 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> Param3 \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_val3\fP\fC [private]\fP"
.PP
Definition at line 42 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> Param4 \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_val4\fP\fC [private]\fP"
.PP
Definition at line 43 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().
.SS "template<class ReturnType, class ClassType, class Param1, class Param2, class Param3, class Param4, class Param5> Param5 \fBDL::Delegate5\fP< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::\fBm_val5\fP\fC [private]\fP"
.PP
Definition at line 44 of file Delegate5.hpp.
.PP
Referenced by DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Delegate5(), and DL::Delegate5< ReturnType, ClassType, Param1, Param2, Param3, Param4, Param5 >::Invoke().

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
