DL::DelegateList
NAME
DL::DelegateList -
SYNOPSIS
#include <DelegateList.hpp>
Public Member Functions
virtual ~DelegateList ()
void add (DelegateObj m_obj)
void reverse_call ()
void call ()
void operator() ()
Private Attributes
std::deque< DelegateBase * > m_obj_list
Constructor & Destructor Documentation
virtual DL::DelegateList::~DelegateList () [inline, virtual]
Definition at line 32 of file DelegateList.hpp.
References stdext::foreach(), and m_obj_list.
Member Function Documentation
void DL::DelegateList::add (DelegateObj m_obj) [inline]
Definition at line 36 of file DelegateList.hpp.
References m_obj_list.
Referenced by main().
void DL::DelegateList::call () [inline]
Definition at line 44 of file DelegateList.hpp.
References stdext::foreach(), and m_obj_list.
Referenced by main().
void DL::DelegateList::operator() () [inline]
DelegateList::operator()() is used to emits all stored Delegates<>
Definition at line 50 of file DelegateList.hpp.
References stdext::foreach(), and m_obj_list.
void DL::DelegateList::reverse_call () [inline]
Definition at line 40 of file DelegateList.hpp.
References stdext::foreach_reverse(), and m_obj_list.
Member Data Documentation
std::deque<DelegateBase*> DL::DelegateList::m_obj_list [private]
Definition at line 55 of file DelegateList.hpp.
Referenced by add(), call(), operator()(), reverse_call(), and ~DelegateList().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.