.TH "DL::Functor7" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Functor7 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Functor7.hpp>\fP
.PP
Inherits \fBDL::DelegateBase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctor7\fP (ReturnType(*function)(Param1, Param2, Param3, Param4, Param5, Param6, Param7), Param1 val1=Param1(), Param2 val2=Param2(), Param3 val3=Param3(), Param4 val4=Param4(), Param5 val5=Param5(), Param6 val6=Param6(), Param7 val7=Param7())"
.br
.ti -1c
.RI "virtual \fB~Functor7\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP ()"
.br
.ti -1c
.RI "ReturnType \fBInvoke\fP (Param1 val1, Param2 val2, Param3 val3, Param4 val4, Param5 val5, Param6 val6, Param7 val7)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctor7\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ReturnType(* \fBm_function\fP )(Param1, Param2, Param3, Param4, Param5, Param6, Param7)"
.br
.ti -1c
.RI "Param1 \fBm_val1\fP"
.br
.ti -1c
.RI "Param2 \fBm_val2\fP"
.br
.ti -1c
.RI "Param3 \fBm_val3\fP"
.br
.ti -1c
.RI "Param4 \fBm_val4\fP"
.br
.ti -1c
.RI "Param5 \fBm_val5\fP"
.br
.ti -1c
.RI "Param6 \fBm_val6\fP"
.br
.ti -1c
.RI "Param7 \fBm_val7\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> class DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >"
Functor for 8 Param
.PP
Definition at line 37 of file Functor7.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBFunctor7\fP ()\fC [inline, private]\fP"
.PP
Definition at line 47 of file Functor7.hpp.
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBFunctor7\fP (ReturnType(*)(Param1, Param2, Param3, Param4, Param5, Param6, Param7) function, Param1 val1 = \fCParam1()\fP, Param2 val2 = \fCParam2()\fP, Param3 val3 = \fCParam3()\fP, Param4 val4 = \fCParam4()\fP, Param5 val5 = \fCParam5()\fP, Param6 val6 = \fCParam6()\fP, Param7 val7 = \fCParam7()\fP)\fC [inline]\fP"
.PP
Definition at line 49 of file Functor7.hpp.
.PP
References DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_function, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val1, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val2, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val3, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val4, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val5, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val6, and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val7.
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> virtual \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::~\fBFunctor7\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 62 of file Functor7.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> ReturnType \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke (Param1 val1, Param2 val2, Param3 val3, Param4 val4, Param5 val5, Param6 val6, Param7 val7)\fC [inline]\fP"
.PP
Definition at line 67 of file Functor7.hpp.
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> void \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke ()\fC [inline, virtual]\fP"
.PP
Implements \fBDL::DelegateBase\fP.
.PP
Definition at line 63 of file Functor7.hpp.
.PP
References DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val1, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val2, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val3, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val4, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val5, DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val6, and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::m_val7.
.SH "Member Data Documentation"
.PP 
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> ReturnType(* \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_function\fP)(Param1, Param2, Param3, Param4, Param5, Param6, Param7)\fC [private]\fP"
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param1 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val1\fP\fC [private]\fP"
.PP
Definition at line 40 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param2 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val2\fP\fC [private]\fP"
.PP
Definition at line 41 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param3 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val3\fP\fC [private]\fP"
.PP
Definition at line 42 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param4 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val4\fP\fC [private]\fP"
.PP
Definition at line 43 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param5 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val5\fP\fC [private]\fP"
.PP
Definition at line 44 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param6 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val6\fP\fC [private]\fP"
.PP
Definition at line 45 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7> Param7 \fBDL::Functor7\fP< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::\fBm_val7\fP\fC [private]\fP"
.PP
Definition at line 46 of file Functor7.hpp.
.PP
Referenced by DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Functor7(), and DL::Functor7< ReturnType, Param1, Param2, Param3, Param4, Param5, Param6, Param7 >::Invoke().

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
