.TH "DL::Functor1" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL::Functor1 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Functor1.hpp>\fP
.PP
Inherits \fBDL::DelegateBase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctor1\fP (ReturnType(*function)(Param1), Param1 val1=Param1())"
.br
.ti -1c
.RI "virtual \fB~Functor1\fP ()"
.br
.ti -1c
.RI "void \fBInvoke\fP ()"
.br
.ti -1c
.RI "ReturnType \fBInvoke\fP (Param1 val1)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctor1\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ReturnType(* \fBm_function\fP )(Param1)"
.br
.ti -1c
.RI "Param1 \fBm_val1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ReturnType, class Param1> class DL::Functor1< ReturnType, Param1 >"
Functor for 1 Param
.PP
Definition at line 31 of file Functor1.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ReturnType, class Param1> \fBDL::Functor1\fP< ReturnType, Param1 >::\fBFunctor1\fP ()\fC [inline, private]\fP"
.PP
Definition at line 35 of file Functor1.hpp.
.SS "template<class ReturnType, class Param1> \fBDL::Functor1\fP< ReturnType, Param1 >::\fBFunctor1\fP (ReturnType(*)(Param1) function, Param1 val1 = \fCParam1()\fP)\fC [inline]\fP"
.PP
Definition at line 37 of file Functor1.hpp.
.PP
References DL::Functor1< ReturnType, Param1 >::m_function, and DL::Functor1< ReturnType, Param1 >::m_val1.
.SS "template<class ReturnType, class Param1> virtual \fBDL::Functor1\fP< ReturnType, Param1 >::~\fBFunctor1\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 41 of file Functor1.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<class ReturnType, class Param1> ReturnType \fBDL::Functor1\fP< ReturnType, Param1 >::Invoke (Param1 val1)\fC [inline]\fP"
.PP
Definition at line 46 of file Functor1.hpp.
.PP
References DL::Functor1< ReturnType, Param1 >::m_function.
.SS "template<class ReturnType, class Param1> void \fBDL::Functor1\fP< ReturnType, Param1 >::Invoke ()\fC [inline, virtual]\fP"
.PP
Implements \fBDL::DelegateBase\fP.
.PP
Definition at line 42 of file Functor1.hpp.
.PP
References DL::Functor1< ReturnType, Param1 >::m_val1.
.SH "Member Data Documentation"
.PP 
.SS "template<class ReturnType, class Param1> ReturnType(* \fBDL::Functor1\fP< ReturnType, Param1 >::\fBm_function\fP)(Param1)\fC [private]\fP"
.PP
Referenced by DL::Functor1< ReturnType, Param1 >::Functor1(), and DL::Functor1< ReturnType, Param1 >::Invoke().
.SS "template<class ReturnType, class Param1> Param1 \fBDL::Functor1\fP< ReturnType, Param1 >::\fBm_val1\fP\fC [private]\fP"
.PP
Definition at line 34 of file Functor1.hpp.
.PP
Referenced by DL::Functor1< ReturnType, Param1 >::Functor1(), and DL::Functor1< ReturnType, Param1 >::Invoke().

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
