.TH "Foobar" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Foobar \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtest0\fP ()"
.br
.ti -1c
.RI "void \fBtest1\fP (int i1)"
.br
.ti -1c
.RI "void \fBtest2\fP (int i1, int i2)"
.br
.ti -1c
.RI "void \fBtest3\fP (int i1, int i2, int i3)"
.br
.ti -1c
.RI "void \fBtest4\fP (int i1, int i2, int i3, int i4)"
.br
.ti -1c
.RI "void \fBtest5\fP (int i1, int i2, int i3, int i4, int i5)"
.br
.ti -1c
.RI "void \fBtest6\fP (int i1, int i2, int i3, int i4, int i5, int i6)"
.br
.ti -1c
.RI "void \fBtest7\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7)"
.br
.ti -1c
.RI "void \fBtest8\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)"
.br
.ti -1c
.RI "void \fBtest9\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)"
.br
.ti -1c
.RI "void \fBtest10\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)"
.br
.ti -1c
.RI "void \fBtest0\fP ()"
.br
.ti -1c
.RI "void \fBtest1\fP (int i1)"
.br
.ti -1c
.RI "void \fBtest2\fP (int i1, int i2)"
.br
.ti -1c
.RI "void \fBtest3\fP (int i1, int i2, int i3)"
.br
.ti -1c
.RI "void \fBtest4\fP (int i1, int i2, int i3, int i4)"
.br
.ti -1c
.RI "void \fBtest5\fP (int i1, int i2, int i3, int i4, int i5)"
.br
.ti -1c
.RI "void \fBtest6\fP (int i1, int i2, int i3, int i4, int i5, int i6)"
.br
.ti -1c
.RI "void \fBtest7\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7)"
.br
.ti -1c
.RI "void \fBtest8\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)"
.br
.ti -1c
.RI "void \fBtest9\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)"
.br
.ti -1c
.RI "void \fBtest10\fP (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Foobar::test0 ()\fC [inline]\fP"
.PP
Definition at line 25 of file DelegateTest3.cc.
.SS "void Foobar::test0 ()\fC [inline]\fP"
.PP
Definition at line 53 of file DelegateTest2.cc.
.SS "void Foobar::test1 (int i1)\fC [inline]\fP"
.PP
Definition at line 27 of file DelegateTest3.cc.
.SS "void Foobar::test1 (int i1)\fC [inline]\fP"
.PP
Definition at line 55 of file DelegateTest2.cc.
.SS "void Foobar::test10 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)\fC [inline]\fP"
.PP
Definition at line 45 of file DelegateTest3.cc.
.SS "void Foobar::test10 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)\fC [inline]\fP"
.PP
Definition at line 73 of file DelegateTest2.cc.
.SS "void Foobar::test2 (int i1, int i2)\fC [inline]\fP"
.PP
Definition at line 29 of file DelegateTest3.cc.
.SS "void Foobar::test2 (int i1, int i2)\fC [inline]\fP"
.PP
Definition at line 57 of file DelegateTest2.cc.
.SS "void Foobar::test3 (int i1, int i2, int i3)\fC [inline]\fP"
.PP
Definition at line 31 of file DelegateTest3.cc.
.SS "void Foobar::test3 (int i1, int i2, int i3)\fC [inline]\fP"
.PP
Definition at line 59 of file DelegateTest2.cc.
.SS "void Foobar::test4 (int i1, int i2, int i3, int i4)\fC [inline]\fP"
.PP
Definition at line 33 of file DelegateTest3.cc.
.SS "void Foobar::test4 (int i1, int i2, int i3, int i4)\fC [inline]\fP"
.PP
Definition at line 61 of file DelegateTest2.cc.
.SS "void Foobar::test5 (int i1, int i2, int i3, int i4, int i5)\fC [inline]\fP"
.PP
Definition at line 35 of file DelegateTest3.cc.
.SS "void Foobar::test5 (int i1, int i2, int i3, int i4, int i5)\fC [inline]\fP"
.PP
Definition at line 63 of file DelegateTest2.cc.
.SS "void Foobar::test6 (int i1, int i2, int i3, int i4, int i5, int i6)\fC [inline]\fP"
.PP
Definition at line 37 of file DelegateTest3.cc.
.SS "void Foobar::test6 (int i1, int i2, int i3, int i4, int i5, int i6)\fC [inline]\fP"
.PP
Definition at line 65 of file DelegateTest2.cc.
.SS "void Foobar::test7 (int i1, int i2, int i3, int i4, int i5, int i6, int i7)\fC [inline]\fP"
.PP
Definition at line 39 of file DelegateTest3.cc.
.SS "void Foobar::test7 (int i1, int i2, int i3, int i4, int i5, int i6, int i7)\fC [inline]\fP"
.PP
Definition at line 67 of file DelegateTest2.cc.
.SS "void Foobar::test8 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)\fC [inline]\fP"
.PP
Definition at line 41 of file DelegateTest3.cc.
.SS "void Foobar::test8 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)\fC [inline]\fP"
.PP
Definition at line 69 of file DelegateTest2.cc.
.SS "void Foobar::test9 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)\fC [inline]\fP"
.PP
Definition at line 43 of file DelegateTest3.cc.
.SS "void Foobar::test9 (int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)\fC [inline]\fP"
.PP
Definition at line 71 of file DelegateTest2.cc.

.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
