/data/callbackext/FunctorN/FunctorN.hpp File Reference.TH "/data/callbackext/FunctorN/FunctorN.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/FunctorN/FunctorN.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Functor0.hpp'\fP
.br
\fC#include 'Functor1.hpp'\fP
.br
\fC#include 'Functor2.hpp'\fP
.br
\fC#include 'Functor3.hpp'\fP
.br
\fC#include 'Functor4.hpp'\fP
.br
\fC#include 'Functor5.hpp'\fP
.br
\fC#include 'Functor6.hpp'\fP
.br
\fC#include 'Functor7.hpp'\fP
.br
\fC#include 'Functor8.hpp'\fP
.br
\fC#include 'Functor9.hpp'\fP
.br
\fC#include 'Functor10.hpp'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_DELEGATES_FUNCTORN_HPP\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_DELEGATES_FUNCTORN_HPP   1"
.PP
Definition at line 19 of file FunctorN.hpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
