/data/callbackext/FunctorN/Functor9.hpp File Reference.TH "/data/callbackext/FunctorN/Functor9.hpp" 3 "11 Mar 2005" "Version 0.0.4" "Extended C++ Callback Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/callbackext/FunctorN/Functor9.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../DelegateN/DelegateBase.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDL\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGUARD_DELGATES_FUNCTOR9_HPP_INCLUDED\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class Param9> \fBDelegateObj\fP \fBcreate_delegate\fP (ReturnType(*Meth)(Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, Param9), Param1 &param1, Param2 &param2, Param3 &param3, Param4 &param4, Param5 &param5, Param6 &param6, Param7 &param7, Param8 &param8, Param9 &param9)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GUARD_DELGATES_FUNCTOR9_HPP_INCLUDED   1"
.PP
Definition at line 19 of file Functor9.hpp.
.SH "Function Documentation"
.PP 
.SS "template<class ReturnType, class Param1, class Param2, class Param3, class Param4, class Param5, class Param6, class Param7, class Param8, class Param9> \fBDelegateObj\fP create_delegate (ReturnType(*)(Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, Param9) Meth, Param1 & param1, Param2 & param2, Param3 & param3, Param4 & param4, Param5 & param5, Param6 & param6, Param7 & param7, Param8 & param8, Param9 & param9)"
.PP
Definition at line 85 of file Functor9.hpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.
