stdext
NAME
stdext -
SYNOPSIS
Functions
template<typename ContainerType, typename Functor> void foreach (ContainerType &cont, Functor func)
template<typename ContainerType, typename Functor> void foreach_reverse (ContainerType &cont, Functor func)
Function Documentation
template<typename ContainerType, typename Functor> void foreach (ContainerType & cont, Functor func)
Definition at line 27 of file AlgorithmExt.hpp.
Referenced by DL::DelegateList::call(), DL::DelegateList::operator()(), DL::Associative< KeyType, Compare >::~Associative(), and DL::DelegateList::~DelegateList().
template<typename ContainerType, typename Functor> void foreach_reverse (ContainerType & cont, Functor func)
Definition at line 33 of file AlgorithmExt.hpp.
Referenced by DL::DelegateList::reverse_call().
Author
Generated automatically by Doxygen for Extended C++ Callback Library from the source code.